---

- name: Check if super user exists
  shell: echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{django_admin_user}}').count()>0)" | {{ virtualenv_path }}/bin/python ./manage.py shell
  args:
    chdir: "{{ app_path }}"
  environment: "{{ django_environment }}"
  register: superuser_exists

- name: Create super user, if doesnt exists already
  django_manage:
    command: "createsuperuser --noinput --username={{ django_admin_user }} --email={{ django_admin_email }}"
    app_path: "{{ app_path}}"
    virtualenv: "{{ virtualenv_path  }}"
    settings: "{{ django_settings_file }}"
  when: superuser_exists.stdout.find('True') == -1

- name: Copy change password expect script
  template:
    src: changepassword.sh.j2
    dest: "{{ app_path }}/changepassword.sh"
    mode: 0755
  when: superuser_exists.stdout.find('True') == -1

- name: Change django super user password
  command: "{{ app_path }}/changepassword.sh"
  args:
    chdir: "{{ app_path }}"
  environment: "{{ django_environment }}"
  when: superuser_exists.stdout.find('True') == -1

- name: remove changepassword.sh script
  file:
    path: "{{ app_path }}/changepassword.sh"
    state: absent
