---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - libav-tools
    - libcurl4-gnutls-dev
    - gnutls-dev
    - expect # for django createsuperuser hack
    - wkhtmltopdf
    - nodejs
    - npm
    - libssl-dev
    - libjpeg-dev
    - gcc
    - "{{ virtualenv_python_version + '-dev' }}"

- name: Install "bower" node.js package globally.
  npm:
    name: bower
    global: yes

- name: Make sure node is in the path
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

