---

- name: Ensure that the application file permissions are set properly
  file:
    path: "{{ virtualenv_path }}"
    recurse: yes
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    state: directory
  changed_when: False
  notify: restart application

- name: Defect Dojo install completed
  debug:
    msg: 'Defect Dojo is installed successfully, please visit site with ip address or hostname https://ip-address or https://hostname'
