---

- name: Install virtualenv
  pip:
    name: virtualenv
  tags: packages

# If virtualenv is not available, it will be created for you.
- name: Ensure gunicorn and pycurl are installed in the virtualenv
  pip:
    virtualenv: "{{ virtualenv_path }}"
    name: "{{ item }}"
  with_items:
    - gunicorn
    - pycurl

- name: Create the Gunicorn script file
  template:
    src: gunicorn_start.j2
    dest: "{{ virtualenv_path }}/bin/gunicorn_start"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0755
    backup: yes
  tags: deploy

- name: Create the application log folder
  file:
    path: "{{ application_log_dir }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0774
    state: directory

- name: Create (or retain) the application log file
  copy:
    content: ""
    dest: "{{ application_log_file }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0664
    force: no

- name: Create the virtualenv postactivate script to set environment variables
  template:
    src: virtualenv_postactivate.j2
    dest: "{{ virtualenv_path }}/bin/postactivate"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0640
    backup: yes
  tags: deploy

- name: Create the maintenance page
  template:
    src: maintenance_off.html
    dest: "{{ virtualenv_path }}/maintenance_off.html"
    mode: 0664
