name-template: '$NEXT_MINOR_VERSION 🌈'
tag-template: '$NEXT_MINOR_VERSION'
branches:
  - master
categories:
  - title: '💣 Breaking changes'
    labels:
      - 'Breaking Changes'
  - title: '🚩 Requires settings change/database migration'
    labels:
      - 'settings_changes'
      - 'New Migration'
  - title: '🚩 Security'
    labels:
      - 'security'
  - title: '🚀 New importers'
    labels:
      - 'Import Scans'
  - title: '🚀 General features and enhancements'
    labels:
      - 'feature'
      - 'enhancement'
      - 'performance'
  - title: ':factory: API features and enhancements'
    labels:
      - 'apiv2'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
