sudo: required

language: python

install: true

env:
  #DockerHub
  - secure: "Ohx+WXYkBXEntk0vNMmDFCZccML5MnmA5HW3phDWv6UanBchAWghC632wIGn0sUQxnDs78TiCWhSMdcCn/7VlopEWdmwpwIF/a8dNwHo3AyQZx5qAz1eHQGbS5DqKZ2JF2xuvb8+fFvPJqPU4q8XZYy7zWG1i0zDF2sw4HCBcWoeH1by7YkNb6YkIuby5Hvrhcayi9jamovddH7AeAGkxTKMz1X0TwxWyB0M1zW9wHuVUn/g7Vb7NQR+DlRr2QshCZePWmiKFHGMT2Y2bwcYuCj6f2HvClUKRIXdM9Fm57N5eCccA/0BZdeNW1YnLL2jlWA8uxzcQomSmW0+m3Yaqq3KnLkO0JM0GtRrTVxDoZvTczJmBC8RW0E6sVMr9TaRBUogfntEPumBMuibCKj8YcnyYxAUN6Cz4hQqE7iDkhHB7K1bOFyrlmFqBZp2pszit9Ref15D885pKKLUkvHtxG4ldxUWU8N0pJKdraBIAVFn8RGlbBd60nYKTN2SHx8xXni2RKAsswXWCxNfXmCUMFKECaIs2d7cQtAouporpDtafSfGdyGhTCSTyIS6b9k/lfTittJlepwxKYvcwuuRU7FEgG3j1tXCghKoQdX9QbNKI41bRyQkdE7VciNULrkTJqQFFGgNQJIFmXN3pLWQjYazJR4L4FBNytW+hBxtspo="
  - secure: "WNSg0OujHd9PR//fCsycCVLrE7Kohyg2Lx58fYtprLT125ZzNCpVyXpN2cfy+ahhTmViR+JD8sUJRVAhCFP1sdeVG+zGRxf6sLJZjtppnFnWHytTcaBn8EYAR5LPRfq+QvkA4bszgGt/7d4Jc0ejIIJGxpTpqw9K7fAZbgLlVBLsJtIy05WX8YgtSSlHs/l2m+k2mFPhCixs4HL8zJGXs6dFPHkJugfKvpDPCePY9xATUrmTywxXFN3Lh0a80HZBQpF/usrKWzjBx366vkYslxDqi7JbaNgRFqQdFj6ax3aynCERWoBLIPOT604qqdlFvujECT5zg6D0G/fC8WMf8aJP25PDx1AJIftVKwtKYsTPrdgclX0UE+NnUzhR1DU6xNN6DHcBbuCu3lOxssguhF2+8US3qgf1vqJKOvIH2bYWlP8x9Rny78xA7JiHHE5z6m9ZcIUEQ9qxvl1+PVU8O7ftupq6fTRNob3m53jl3rcrfTD/VR3s0KXtYs5D0b4VSElIVBcbTYcTEbTMyK6hDcNl/OZvurL+rYfg/uutwwKOx49NOeKOrihVrW1p6VywVLM5viPEzNu2cRL2vTvxNcb21SVpU81Kt52wOgyVXETkt+FcT7YKXwwaxLTT3s/SJXsQXIRYmVfQHkwmhY9lt/3vx3mSzJigY+qN+VLTGxI="
  - COMMIT=${TRAVIS_COMMIT::8}
services:
  - docker

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  ## Docker Build
  - export DOJO_ADMIN_USER=test_user
  - export DOJO_ADMIN_PASSWORD=test_password
  - export REPO=appsecpipeline/django-defectdojo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:${TRAVIS_COMMIT::8} .
  - docker run -e DOJO_ADMIN_USER=$DOJO_ADMIN_USER -e DOJO_ADMIN_PASSWORD=$DOJO_ADMIN_PASSWORD --name dojo -d -p 127.0.0.1:8000:8000 $REPO:${TRAVIS_COMMIT::8} bash /django-DefectDojo/docker/docker-startup.bash
  - docker logs dojo
  - docker run -d --name zap --link dojo -p 127.0.0.1:8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
  - docker ps -a
  - docker logs dojo
  - echo "Checking to see if dojo is running"
  - curl http://localhost:8000/login?next=/
  ## Selenium and ZAP requirements
  - pip install selenium==2.53.6
  - pip install requests
  - pip install python-owasp-zap-v2.4
  - pip install prettytable
  - pip install bandit

after_success:
  ## Run the SRC:CLR Scan
  - curl -sSL https://download.sourceclear.com/ci.sh | bash
  ## Run Bandit python static code
  - bandit -r * -x venv,tests,ansible
  ## Run Docker Bench for Security
  - git clone https://github.com/docker/docker-bench-security.git
  - cd docker-bench-security
  - sh docker-bench-security.sh
  #Push to docker repo
  - echo $DOCKER_USER
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

script:
  - python tests/check_status.py -v && python tests/smoke_test.py && python tests/zap.py

addons:
  firefox: "45.0"
