---
version: '3.7'
services:
  uwsgi:
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-uwsgi-dev.sh']
    volumes:
      - '.:/app:z'
    environment:
      DD_DEBUG: 'on'
  nginx:
    volumes:
      - './dojo/static/dojo:/usr/share/nginx/html/static/dojo'
