---

- name: Ensure locale is available
  locale_gen: name=en_US.UTF-8

- name: Install MySQL
  apt:
    name: "{{ item }}"
    update_cache: "{{ update_apt_cache }}"
    state: present
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - "{{ base_python_package }}-mysqldb"
  tags: packages

- name: Ensure the MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure database is created
  mysql_db:
    name: '{{ db_name }}'
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- name: Ensure user has access to the database
  mysql_user:
    name: "{{ db_user }}"
    host: "{{ db_host | default('localhost') }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
