{{- if .Values.django.ingress.enabled -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: {{ $fullName }}-nginx
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.django.ingress.secretName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-django
              servicePort: http
{{- end }}
