{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  DD_ADMIN_PASSWORD: {{ randAlphaNum 22 | b64enc | quote }}
