---

# Virtualenv settings.
virtualenv_python_version: "{{ base_python_package }}"

# Application settings.
virtualenv_path: "/opt/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
app_path: "{{ project_path }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"

# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: "{{ application_name }}"


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host }}"
  EMAIL_HOST_USER: "{{ email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
  BROKER_URL: "{{ broker_url|default('') }}"
