---
# You should never expose creds/tokens/keys in github repositories, so please use ansible-vault to encrypt this file or use third party vault like consul vault from hashicorp.
#
# To encrypt:
# ansible-vault encrypt vars/production.yml --vault-password-file ~/.vault_pass.txt
#
# To Edit and re-encrypt
# cd ansible && ansible-vault edit vars/production.yml --vault-password-file ~/.vault_pass.txt


# Git settings.
setup_git_repo: yes
git_branch: master

# Ansible will login as following user
server_user: ubuntu

requirements_file: "{{ project_path }}/requirements.txt"
bower_dir: "{{ project_path }}/components/"

ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIEaDCCA1CgAwIBAgIJAI5475MlWW9oMA0GCSqGSIb3DQEBBQUAMH8xCzAJBgNV
  BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
  c2NvMRowGAYDVQQKExFPV0FTUCBEZWZlY3QgRG9qbzERMA8GA1UECxMIRGVmZW5k
  ZXIxFDASBgNVBAMTC2RlZmVjdC5kb2pvMB4XDTE3MTEwOTEzMTg1MFoXDTE4MTEw
  OTEzMTg1MFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAU
  BgNVBAcTDVNhbiBGcmFuY2lzY28xGjAYBgNVBAoTEU9XQVNQIERlZmVjdCBEb2pv
  MREwDwYDVQQLEwhEZWZlbmRlcjEUMBIGA1UEAxMLZGVmZWN0LmRvam8wggEiMA0G
  CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+IAjAanvD0+tMT+cn0iu0eOLzCI32
  rZiO03goHZ74gz8Ge1okSd4ltCQqsUF/DnMJZHkelsmLJTWGuNIMeDEz6JJhux1p
  qBwjGjiRAI60kAU58+FOlvtDTw0g6I1z0vj0I/HWnAves5gAbhVFl9iigjOrkh9O
  ifwKhDLaAIPij+DGPVpHzlFz3+azTG/9JwKvfVghGtY4M7yPc6cpRxY9yf89gKCA
  NWWbvHDARnrt61alad7N7yu1Z7BZBlcJkcGYgT4P6aKhLMoJXhVY9f6YKCY9hEt5
  UyfvHsG39kLf9+1n2vgZl7/WnCb0y4Mat+IVm6f0A7ZrkBEPRLPEmwfRAgMBAAGj
  geYwgeMwHQYDVR0OBBYEFKfYXDNGwvDhuNYgLCI/LuqhPRb0MIGzBgNVHSMEgasw
  gaiAFKfYXDNGwvDhuNYgLCI/LuqhPRb0oYGEpIGBMH8xCzAJBgNVBAYTAlVTMRMw
  EQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRowGAYD
  VQQKExFPV0FTUCBEZWZlY3QgRG9qbzERMA8GA1UECxMIRGVmZW5kZXIxFDASBgNV
  BAMTC2RlZmVjdC5kb2pvggkAjnjvkyVZb2gwDAYDVR0TBAUwAwEB/zANBgkqhkiG
  9w0BAQUFAAOCAQEAeWv27m3MrtERxylDL6JkSOLb3I9Bb5+nlbAxegmB1Vnp83O9
  EUMVqlb8Ij5DwLXKdHlYqi+nfMN1vL9KBCqgJRocVRAn8B6X8MqF+0GddPFCkYtu
  H50SEd7wCelr+AI+7896YnTn3qzHNyBnbGHrHbp274GwXSo58oYBvUKWfdBerVCt
  D/MvxMFkQPyfUOm2/4tDq6PE3dKdxJOzo6BBhzJHPyehOH8DYXtFZ3MsxfDmPaOT
  l5WBimeVfOUttRxfYbPEsx7fz1XkAJkgU93EBVQfJQG5X5L19eW4olcBj8GmhBml
  zXtVkjxWW8C4xv1Ez7jFND8x3mtvq1bgvc8fcQ==
  -----END CERTIFICATE-----

# This key is for demo purposes only. If you're committing your keys
# to your git repo, you'd probably want it encrypted. You can use
# ansible-vault to do this.

ssl_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAviAIwGp7w9PrTE/nJ9IrtHji8wiN9q2YjtN4KB2e+IM/Bnta
  JEneJbQkKrFBfw5zCWR5HpbJiyU1hrjSDHgxM+iSYbsdaagcIxo4kQCOtJAFOfPh
  Tpb7Q08NIOiNc9L49CPx1pwL3rOYAG4VRZfYooIzq5IfTon8CoQy2gCD4o/gxj1a
  R85Rc9/ms0xv/ScCr31YIRrWODO8j3OnKUcWPcn/PYCggDVlm7xwwEZ67etWpWne
  ze8rtWewWQZXCZHBmIE+D+mioSzKCV4VWPX+mCgmPYRLeVMn7x7Bt/ZC3/ftZ9r4
  GZe/1pwm9MuDGrfiFZun9AO2a5ARD0SzxJsH0QIDAQABAoIBADmclWpRGg3eIpfu
  QnpzmmDGnObOOc59DhSBihCF4U0m4CtDp64FYDaGnsr9CX7JzxwSgQ0+3fW3IcAg
  My4qIaa8G9dXjvMcSOJuKKPvyk52sc680xIweBUOWEkXjv2A+YVpevfwMzyZqT7A
  HNwIxlGAKM4dqjTvZRt+sbYTn+M/9kS1zICi9NA3bpgZzRoc2Ny7WBtqkXXGepvF
  aXuNo3TOGQc9xBQ6Ra9DolX3awNqf9GdUB4CFFpmQjR2alLTBK+THlkOKS/iC2xX
  iaOTWF2E+V046vj+oLWKDc3rELrDuEmwvXjzUuKZ4vC/fG/1yesf+ESvTFrVUYIz
  5zz3m9ECgYEA3eftdX45BzIONwe22d41Mew45143SuLa63Kcbe4CFhKSigs1Emnh
  VIXM+0VWDRCAkcLZ/vf9zi/kZOhgfZYgKflJfZt8pwMpbRqVD8VXaEzVLUWtb+WH
  JJrNCmjxBlID204eje4TXpPg9PxScU8qqx5VZAhUFYBoPQLriX/rXy0CgYEA21YX
  4U0g8a5/unqUu6W4KvPqNNWsz6ncP1BGasI8SUsGMOVt8Zra4XW5MYZP5jdgO/Tk
  IfLrQ2X/6np5wKIG5pjDEISO/GPfTaOhxPC3tlEiLprDdFXchGQF+kpApGskaSxT
  BEwe6vzg5N/81nPguTDSIFVYZT637loP5oqR0bUCgYEAzICKMSZzDfOOcB6W36/N
  3EUzp94HHOd2E1gbW5/lokvZaoirj12ugIOShdq/U+jqY+prlnMbHyK53FjfW723
  xJbtqGlb9lqOmfLOfqtCQ2fTahZ1oNKpug1Dex19SnLZBQm4VNqcVSP5RC0pGS15
  SBv7W+Xk/6/H4LpJMP2Hf70CgYAqYvvgbWBVdEx4xCGkFcV+f36eUUDBLOlETwYc
  sYam/1ml72CM1UlBUtfEK1mbes4dKBlCOkie0MJhFOQchvNgctsXgRaEzeQkg9/K
  SF6oXAuICB6Hh+RCrXW+RcUyQQZbUNaGOROsg8wOTv70jpY6E6Y322ZmwnUXGc6C
  1fqSFQKBgHBRbdhjY6k5cnx46gM4UT0zSltu06b42JHotW39tj5yz9U+bebEexw3
  2CqwdGox7hI77QbRjO857EF2+9DnuYUi5tBbS+3abC0etgXnTYTnHGKja39VQ44X
  qO/XvIB0yM6EOFcRjUzL0ouGcwOqc3VN1bFPTvVb9ZXPVGOUe8LX
  -----END RSA PRIVATE KEY-----

# Database settings.
# db_type can have either MySQL or PostgreSQL
db_type: 'MySQL'
db_user: "{{ application_name }}"
db_name: "dojodb"
db_host: "localhost"
db_password: "Cu3zehoh7eegoogohdoh1thehax0rthematr1x"

# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 300

# Nginx settings.
nginx_server_name: "{{ inventory_hostname }}"
nginx_strong_dh_group: no

# Application settings.
django_fixtures_file: product_type test_type development_environment system_settings
django_settings_file: "dojo.settings"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"

run_django_syncdb: yes
run_django_db_migrations: yes
run_django_collectstatic: yes
run_django_loaddata: yes
run_django_bower: yes

# Django super user settings
django_admin_user: admin
django_admin_password: "Cu3zehoh7eegoogohdoh1thehax0rthematr1x"
django_admin_email: admin@example.com

# Email settings.
email_host: smtp.gmail.com
email_host_user: admin@example.com
email_host_password: mypassword
email_port: 25
email_use_tls: True
