name: Cancel outdated workflow runs
on: [push]
jobs:
  cancel:
    name: 'Cancel Outdated Workflow Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: ['integration-tests.yml', 'k8s-testing.yml', 'unit-tests.yml']
          access_token: ${{ github.token }}
