name: Release Drafter

on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: valentijnscholten/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
