name: Test Valentijn
# pull requests: 
#
# dev, master:
#      run on every push, which is when something gets merged also
on: 
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set unit-test mode
        run: docker/setEnv.sh unit_tests_cicd
      
      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - run: docker-compose pull

      - name: Build the stack
        run: docker-compose build

      # phased startup so we can use the exit code from integrationtest container
      - name: Stary MySQL
        run: docker-compose up -d 

      - name: Initialize
        run: docker-compose up --exit-code-from initializer initializer

      - name: Unit tests
        run: docker-compose up --exit-code-from uwsgi uwsgi

      - name: Logs
        if: failure()
        run: docker-compose logs --tail="2500" uwsgi

      - name: Shutdown
        if: always()
        run: docker-compose down
