---

- name: Initial configuration for a {{ application_name }} server
  hosts: all
  become: yes
  become_user: root
  remote_user: ubuntu 
  vars:
    - update_apt_cache: yes
  vars_files:
    - vars/base.yml
    - vars/{{ env }}.yml
    - roles/common/defaults/main.yml

  roles:
    - security
